# Generated by Django 4.2.7 on 2023-12-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diahorario',
            name='horaEntrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diahorario',
            name='horaSalida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='diaHorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencias.diahorario'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='tipoMarca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencias.tipomarca'),
        ),
    ]
