# Generated by Django 4.2.7 on 2023-12-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_alter_diahorario_horaentrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='fechaBajada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
