# Generated by Django 4.2.7 on 2024-05-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0003_horario_fechabajada'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
