# Generated by Django 4.2.7 on 2024-08-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0004_empleado_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(max_length=300)),
                ('estaJustificada', models.BooleanField(blank=True, default=False, null=True)),
                ('justificacion', models.TextField(blank=True, max_length=300, null=True)),
                ('docs', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencias.empleado')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencias.marca')),
                ('tipoFalta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencias.tipofalta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
