# Generated by Django 4.2.7 on 2024-08-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0005_tipofalta_falta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipofalta',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tipofalta',
            name='nombre',
            field=models.TextField(max_length=300),
        ),
    ]
