# Generated by Django 4.2.7 on 2024-08-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0006_alter_tipofalta_descripcion_alter_tipofalta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipofalta',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
