# Generated by Django 4.2.7 on 2024-08-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0007_alter_tipofalta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='falta',
            name='fechaHora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='falta',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
